### ISSUE TITLE
Perfomance issue (Freezy)

### ISSUE THREAD

**Issue by timsofteng** [leafOfTree/vim-matchtag#2] opened 2020-09-07 11:16 UTC
Hey. I used this plugin and it's great.
But perfomance isn't great. 

Please try to open some big html file for production (all in single line) and try to scroll by press and hold h or l key. You will see some freezes. It can be reproduced in all terminals emulators.

**Comment by leafOfTree** [comment] 2020-09-10 02:08
Hi, thank you for the feedback. It is probably caused by the `<`,`>` operators in the `<script>` tag. The freezes happen when the cursor moves across them. I'll try to fix it later.
```html
<script>!function(e){ function r(r){ for(var n,a,i=r[0],c=r[1],l=r[2],p=0,s=[];p<i.length;p++)for(var l=0;l<i.length;l++)r(i[l]);var f=c;t() }([])</script>

```

**Comment by timsofteng** [comment] 2020-09-11 08:38
It freezes not only inside <script> tag. I caught this bug in big raw htm filel with inline css styles.

**Comment by leafOfTree** [comment] 2020-09-11 23:29
Yes, I see. It is the  `>` in the CSS selector that also causes it.

**Comment by leafOfTree** [comment] 2020-09-17 05:47
Hey, there. I checked the performance issue and found that actually it was caused by inefficient `getline()` calls on long lines. I've improved the speed by avoiding `getline()` and using cache. Hopefully, it should be smooth in big long files at present.

By the way, the `>` and `<`  freeze seems to be related to the file syntax.

**Comment by leafOfTree** [comment] 2020-09-17 06:02
And I added a helper function to see how long it takes
```vim
call matchtag#ReportTime()
```

**Comment by timsofteng** [comment] 2020-09-17 13:38
Looks like it helps. Thanks!

**Comment by timsofteng** [comment] 2020-09-17 15:57
Oh, no. I was wrong. It's still freezy on big vue files.

**Comment by leafOfTree** [comment] 2020-09-18 01:47
Hmm, I'll check it.

**Comment by leafOfTree** [comment] 2020-09-18 02:32
It turns out that the cache was disabled by mistake.
```diff
let s:disable_cache = s:GetConfig('disable_cache',
-      \ s:exists_text_changed)
+      \ !s:exists_text_changed)
```
Now that it should reduce the freezy when browsing the file. 
For editing, did you find which context has more freezes, template, script, or style?

**Comment by leafOfTree** [comment] 2020-09-21 02:58
Hi, I also introduced two configs to optimize performance. They help to only run when it has required syntax.
```vim
let g:vim_matchtag_skip = '^javascript\|script$\|style$'
let g:vim_matchtag_skip_except = 'html\|template'
```

**Comment by leafOfTree** [comment] 2021-08-10 06:16
Hi, I'll close this issue. Please let me know if any other problems.

**Closed as completed by leafOfTree** 2021-08-10 06:16 UTC
Labels: bug
